run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  gofmt:
    simplify: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gocyclo
    - misspell
    - unconvert

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
    - path: _test\.go
      text: "fieldalignment"
